### ISSUE TITLE
📔 nnist-pt-20230125

### ISSUE THREAD

**Issue by newojima** [nejilabs/nnist-pt-20230125#1]
<div width="100%" align="center">

<a href="https://github.com/nejilabs"><img src="https://img.shields.io/badge/🔗Link-333333?style=for-the-badge"/></a>

<a href="https://github.com/nejilabs"><img src="https://img.shields.io/badge/👤@nejilabs-333333?style=for-the-badge"></a>

<img src="https://img.shields.io/badge/📅2023/01/25-333333?style=for-the-badge">

<img src="https://img.shields.io/badge/⌛-e7b416?style=for-the-badge"><img src="https://img.shields.io/badge/In%20Progress-333333?style=for-the-badge">

<a href="https://github.com/nejilabs"><img src="https://user-images.githubusercontent.com/31657420/214573139-256234ca-bd0b-4e27-b373-c090a37825f5.png" width="100%" /></a>

<h1><a href="https://github.com/nejilabs/nnist-pt-20230125/issues/1">nnist-pt-20230125</a></h1>

<h3> Nejilabs NIST Project Template </h3>

</div>

<div align="left"> 
<details open>
<summary> 
<b>Description:</b> Nejilabs NIST Project Template used to generate NIST projects along with a standardised design for README.md notes, issues and pull request templates.

</summary>

<br/>

In the long term, after we further develop and perfected this project template in Nejilabs, we then create a new project template repo based from this and store it to https://github.com/nejima-kaihatsu (parent). 

We then develop that repo to be known as the "Universal Project Template", where it shall dictate the standards and stuff of what projects under the Nejima Group should have (issue & pr templates, common actions and workflows, etc.).

The Universal Project template shall then be shared / forked to its subsidiaries to generate their projects from, while adapting to the branding specs of each according subsidiary.

</details>

---

# Todos
- [x] ~~Further personalise the general issues templates~~
- [ ] merge cover issue and cover readme template design (with notes section disabled / commented out by default).
- [ ] make the default thumbnail into an asset instead.
- [ ] Finalise Project Template
- [ ] Create new project template based from this and store it to (https://github.com/nejima-kaihatsu)
- [ ] Develop the new project template  into the "Universal Project Template shared among the orgs and its subsidiaries"

---

# Contents

## 1- Cover Issues Template Design
- [x] #5 
- [x] #6

## 2 - Cover READMEs Template Design
- [x] #8 
- [x] #9 

## 3 - Chapter Issues Template Design
- [x] #7 

## 4 - Pull Request Template Design
- [x] #11 

## 5 - Other Issues Designs
- [x] #12 
- [x] #13 
- [x] #14

**Comment by newojima** [comment]
dont u think it would be better to componentalise these templates? maybe by following atomic design principle where we divide them to smaller reusable components atoms, molecules, organisms like that?

**Comment by newojima** [comment]
well, sure. lets have those too and see how we behave, if we prefer a prebuilt barebones template, interchangeble sample temp;ate, or building it our own way using smaller templated components. but as much as possible we want uniformity and standardisation *"in style-by style"* :sunglasses:

**Comment by newojima** [comment]
# Main Common Components:

## Cover Templates

- Top Buttons
    - Link Button to the course / article / repo.
    - Link Button to the author / creator / channel / etc.
    - Date of Creation
    - Status + Timestamp
- Thumbnail
- Name
    - name we named the project repo
    - their real name (ex: full title of course video / article)
- Description

Interchangeables:
- if cover issue: content section
    - task format 
- if cover readme: notes section
    - table of contents
    - section for the notes  

## Chapter Templates

**Comment by newojima** [comment]
# Atoms

# Molecules

# Organisms

# Templates
## Cover Templates
- Cover Issue
- Cover README
## Chapter Templates
- Chapter Issue
- ~~Chapter README~~

## Other Issue Templates
...
## Pull Request Templates
...

**Comment by newojima** [comment]
i think for the pull request template. i would like a reminder to check if im merging to the correct branch, and / or also with the correct branch.

**Comment by newojima** [comment]
> i think for the pull request template. i would like a reminder to check if im merging to the correct branch, and / or also with the correct branch.

<img src="https://media.tenor.com/zT9-mg-702UAAAAC/knuckles-do-you-know-the-way.gif" />
think this would be a great reminder for the pull requests in my projects :thinking:

**Comment by newojima** [comment]
> i think for the pull request template. i would like a reminder to check if im merging to the correct branch, and / or also with the correct branch.

<img src="https://media.tenor.com/5yqEU7Pd_QIAAAAC/adventure-time-bmo.gif" />
this is another option. cuter reminder. but think like the other one better.

**Comment by newojima** [comment]
we can implement instead an action for every creation of pull request as its dispatcher. but tbh normally i dont add anything in prs, and it seems empty.

i think having em as templates would be faster cuz the action might take longer since it still gets dispatched and needs to run, while having them directly on templates would be rather instant.

it would be like having a communication with github, treatin em like a friend u know who watchin yo back :sweat_smile: ?

**Comment by newojima** [comment]
<img src="https://media.tenor.com/vf5NFUHXmXMAAAAd/mikasa-staring.gif" />
oh it be great if all were anime themed ryt? we could also use this but with a caption stating "Did you double check?" :sweat_smile:

**Comment by newojima** [comment]
honestly if we implement an action pr checker, we could have these options randomised - more dynamic and fun. but were just starting out. lets stick with the first one for now. make this a future project instead.

**Comment by newojima** [comment]
for pr templates: 
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by newojima** [comment]
# For Linking Issues
  
| Linked issue	| Syntax	| Example | 
|---|---|---|
| Issue in the same repository | KEYWORD #ISSUE-NUMBER	| Closes #10
| Issue in a different repository	| KEYWORD OWNER/REPOSITORY#ISSUE-NUMBER	| Fixes octo-org/octo-repo#100
| Multiple issues	| Use full syntax for each issue	| Resolves #10, resolves #123, resolves octo-org/octo-repo#100

**Comment by newojima** [comment]
this is the pr temp i came up with :rofl: :

<details open><summary>Guardian Ugandan Knuckles</summary>
  
### Enters: The Wise Guardian Ugandan Knuckles...
  
<img src="https://media.tenor.com/zT9-mg-702UAAAAC/knuckles-do-you-know-the-way.gif" width="100%" />
  
### 1 - Double Check - Triple Check 
Check if you are merging to the correct branch. And with the Correct Branch pls. 🙏

### 2 - For Linking Issues in PRs
  
| Linked issue	| Syntax	on PR's Description| Example | 
|---|---|---|
| Issue in the same repository | KEYWORD #ISSUE-NUMBER	| Closes #10
| Issue in a different repository	| KEYWORD OWNER/REPOSITORY#ISSUE-NUMBER	| Fixes octo-org/octo-repo#100
| Multiple issues	| Use full syntax for each issue	| Resolves #10, resolves #123, resolves octo-org/octo-repo#100

otherwise u can manually link them after. 👍

</details>

---

# Have anything to say to dear ol'guardian ugandan knuckles?
## For Merging...
- [ ] Double-checked?
- [ ] Triple-checked?

## Anything else to declare? (Short Description of PR and Affected Issues)

- [ ] Thx Knuckles!

**Comment by newojima** [comment]
@newojima make feature request & bug issues temps

**Comment by newojima** [comment]
> @newojima make feature request & bug issues temps

done

**Comment by newojima** [comment]
![Screenshot_select-area_20230128211030](https://user-images.githubusercontent.com/31657420/215265768-e1335a9a-d996-429e-9cd6-b5f9c8085bd7.png)

Yep Lookin Good. I think just the contact links left through our issue templates config.yml @newojima

**Comment by newojima** [comment]
as for the "componentalised" templates. nah just get them from the samples or barebone templates ^^

**Comment by newojima** [comment]
https://engineeringfordatascience.com/posts/gitmoji/

ooo this would be cool. adding emojis to commit messages would be really nice.

**Comment by newojima** [comment]
ok so cuz in the future once we perfected the design of this for project template with nejilab's research projects, well transfer this repo or perhaps create a new one based on this to nejima-kaihatsu (https://github.com/nejima-kaihatsu) where we will establish that repo as the "universal project template" which is forked to its subsidiaries and suited with their according branding for their own projects. the forks then will get the master branch version of the universal project template whenever theres gonna be a massive change to the standard design for all our projects shared among all of us. thus called "universal"

so did these tests:
1. tried to fork this and if it is possible to generate a project from a forked project template
https://github.com/nejilabs/nnist-pt-20230125 
it has the sync fork to sync with where it was forked from however no issues tab :/. but thats not that bad actually. 

2. tried to generate a project from the forked project template and it was a success. this time it was like a normal repo that was generated from a normal project template. which fits our expectations and requirements, hence a success and it has been determined it was truly possible given the kind of system we want to implement in the future for the long run.
https://github.com/nejilabs/nnist-gpffptt-20230129

**Comment by newojima** [comment]
perhaps in the future we can implement github actions useful for our projects. but thats in the future. we call this a major success for a bright future!

**Comment by newojima** [comment]
actually i think its best we create a new repo to @nejima-kaihatsu instead of transferring this repo there and change it accordingly. for documentation purposes? afterall this is counted as a research project for experiment?

**Comment by newojima** [comment]
dont u think itll be better to just merge the cover issue and cover readme template designs. then by default well just comment out the notes section. cuz usually we compile the notes at the end of the project, while we take the quick dirty notes using the github issues along the project cover tracker issue.

**Comment by newojima** [comment]
implemented new colors and varying emojis for project status:

```md
<!-- Start: Status -->
<!-- Color Palette | Sources: https://www.color-hex.com/color-palette/35021| https://www.astrouxds.com/img/patterns/status-system-fundamentals.png
✨TODO - 2dccff, 
🚧ONGOING - ffb302
⏳STANDBY - 964B00,
✔️DONE - 56f000
❌CANCELLED - ff3838,
💀FAILED - 9ea7ad
 -->
<img src="https://img.shields.io/badge/.-9ea7ad?style=for-the-badge"><img src="https://img.shields.io/badge/💀FAILED  -333333?style=for-the-badge">
<!-- End: Status -->
```

**Comment by newojima** [comment]
![Screenshot_select-area_20230130175006](https://user-images.githubusercontent.com/31657420/215430273-1e445210-626c-4596-b800-dfe84ad460d2.png)

maybe improve the layout for this kind of view for our project cover issues
